### PR TITLE
Add English docs

### PR DESCRIPTION
**Pull request by micael-grilo**
Add new document structure, for new version of dados.gov. 
EN translations will be done later.

### CODE REVIEW

**Comment by waldyrious** [comment]
The actual added content is almost all in Portuguese still. Perhaps this should be kept as a draft PR for the time being?

**Comment by micael-grilo** [comment]
@waldyrious, the purpose here is just to define the new document structure as we will need this in the new version of dados.gov. Regarding translations, it will be done in the near future if you want to contribute or you know some translator willing to contribute please let us know. ;) Thanks

**Comment by waldyrious** [comment]
If only the structure is important for the current step, rather than the content, perhaps the text could be either removed or commented out, leaving a placeholder message visible ("coming soon" or something like that)? Maybe the placeholder message could even point people to the places where they could contribute -- e.g. a GitHub link to the relevant `.md` file where a logged-in user could simply click the pencil icon to edit and propose a PR.

**Comment by andrelapa** [comment]
@waldyrious  Thanks for the input. We will have the translations soon, they are being finalized, and can hopefully be pulled just in time for the next release.

**Pull request merged**
